language: rust

matrix:
  include:
    - env: TARGET=thumbv6m-none-eabi
      rust: nightly

install:
  - rustup target add $TARGET

script:
  - cd narc_rust/hal && cargo check
  - cd ../app && cargo check

